# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('product', '0001_initial'), ('product', '0002_auto_20170721_0604'), ('product', '0003_auto_20170721_0624'), ('product', '0004_auto_20170721_0625'), ('product', '0005_productcategorytop__order')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='상품명')),
                ('short_description', models.CharField(blank=True, max_length=60, verbose_name='짧은 설명')),
                ('full_description', models.TextField(blank=True, verbose_name='상세 설명')),
                ('use_price', models.BooleanField(default=False, verbose_name='가격 사용 여부')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryMiddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategorySmall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='소분류명')),
                ('middle_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategoryMiddle', verbose_name='중분류')),
            ],
            options={
                'abstract': False,
                'verbose_name': '소분류',
                'verbose_name_plural': '소분류 목록',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='카테고리명')),
                ('_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'verbose_name': '최상위 카테고리',
                'verbose_name_plural': '최상위 카테고리 목록',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_set', to='product.Product')),
            ],
            options={
                'abstract': False,
                'verbose_name': '상품 가격',
                'verbose_name_plural': '상품 가격 목록',
            },
        ),
        migrations.AddField(
            model_name='productcategorymiddle',
            name='top_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategoryTop'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategorySmall', verbose_name='카테고리'),
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '상품', 'verbose_name_plural': '상품 목록'},
        ),
        migrations.AlterModelOptions(
            name='productcategorymiddle',
            options={'verbose_name': '중분류', 'verbose_name_plural': '중분류 목록'},
        ),
        migrations.AlterField(
            model_name='productcategorymiddle',
            name='title',
            field=models.CharField(max_length=50, verbose_name='중분류명'),
        ),
        migrations.AlterField(
            model_name='productcategorymiddle',
            name='top_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategoryTop', verbose_name='최상위 카테고리'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='productcategorymiddle',
            order_with_respect_to='top_category',
        ),
        migrations.AlterOrderWithRespectTo(
            name='productcategorysmall',
            order_with_respect_to='middle_category',
        ),
        migrations.AlterModelOptions(
            name='productcategorymiddle',
            options={'ordering': ('order',), 'verbose_name': '중분류', 'verbose_name_plural': '중분류 목록'},
        ),
        migrations.AddField(
            model_name='productcategorymiddle',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterOrderWithRespectTo(
            name='productcategorymiddle',
            order_with_respect_to=None,
        ),
        migrations.AlterModelOptions(
            name='productcategorymiddle',
            options={'verbose_name': '중분류', 'verbose_name_plural': '중분류 목록'},
        ),
        migrations.RemoveField(
            model_name='productcategorymiddle',
            name='order',
        ),
        migrations.AlterOrderWithRespectTo(
            name='productcategorymiddle',
            order_with_respect_to='top_category',
        ),
    ]
