# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_category_to_title',
            field=models.BooleanField(default=False, verbose_name='상품명 앞에 카테고리명을 사용'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_size_as_title',
            field=models.BooleanField(default=False, verbose_name='사이즈를 상품명으로 사용'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=60, verbose_name='상품명'),
        ),
    ]
