# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20170827_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_size_to_title',
            field=models.BooleanField(default=False, verbose_name='상품명 뒤에 사이즈를 추가'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_category_to_title',
            field=models.BooleanField(default=False, verbose_name='상품명 앞에 카테고리명을 추가'),
        ),
        migrations.AlterField(
            model_name='product',
            name='use_price',
            field=models.BooleanField(default=False, verbose_name='자체 가격 사용 여부 (옵션 없음)'),
        ),
    ]
