language: python

services:
  - postgresql

python:
  - 3.5

before_install:
  - openssl aes-256-cbc -K $encrypted_04e0b61f42fd_key -iv $encrypted_04e0b61f42fd_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python greenwrap/manage.py migrate --noinput
  - MODE='DEBUG' greenwrap/manage.py test