language: python
services:
- postgresql
python:
- 3.6
env:
- MODE=DEBUG
before_install:
- openssl aes-256-cbc -K $encrypted_50b936b9edbc_key -iv $encrypted_50b936b9edbc_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
install:
- pip install -r .requirements/debug.txt
before_script:
- psql -c "CREATE DATABASE travisci;" -U postgres
- cd greenwrap
script:
- python manage.py migrate --noinput
- python manage.py test
