# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_squashed_0005_productcategorytop__order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['_order'], 'verbose_name': '상품', 'verbose_name_plural': '상품 목록'},
        ),
        migrations.AlterModelOptions(
            name='productcategorytop',
            options={'ordering': ['_order'], 'verbose_name': '최상위 카테고리', 'verbose_name_plural': '최상위 카테고리 목록'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ['-start_date'], 'verbose_name': '상품 가격', 'verbose_name_plural': '상품 가격 목록'},
        ),
        migrations.AddField(
            model_name='product',
            name='_order',
            field=models.PositiveIntegerField(default=0, verbose_name='순서'),
        ),
        migrations.AlterField(
            model_name='productcategorysmall',
            name='middle_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category_small_set', to='product.ProductCategoryMiddle', verbose_name='중분류'),
        ),
        migrations.AlterField(
            model_name='productcategorysmall',
            name='title',
            field=models.CharField(default='미분류', max_length=50, verbose_name='소분류명'),
        ),
        migrations.AlterField(
            model_name='productcategorytop',
            name='_order',
            field=models.PositiveIntegerField(default=0, verbose_name='순서'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.IntegerField(default=0, verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_set', to='product.Product', verbose_name='상품 가격'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='시작일자'),
        ),
    ]
