# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170722_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOptionPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='시작일자')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_set', to='product.ProductOption')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='product.ProductCategorySmall', verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='productcategorymiddle',
            name='top_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_set', to='product.ProductCategoryTop', verbose_name='최상위 카테고리'),
        ),
        migrations.AlterField(
            model_name='productcategorysmall',
            name='middle_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_set', to='product.ProductCategoryMiddle', verbose_name='중분류'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_set', to='product.Product', verbose_name='상품 가격'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_set', to='product.Product'),
        ),
    ]
