# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170722_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoption',
            options={'ordering': ['_order'], 'verbose_name': '상품 옵션', 'verbose_name_plural': '상품 옵션 목록'},
        ),
        migrations.AlterModelOptions(
            name='productoptionprice',
            options={'verbose_name': '상품 옵션 가격', 'verbose_name_plural': '상품 옵션 가격 목록'},
        ),
        migrations.AddField(
            model_name='productoption',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='단위수량'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_set', to='product.Product', verbose_name='상품'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='title',
            field=models.CharField(max_length=100, verbose_name='옵션명'),
        ),
        migrations.AlterField(
            model_name='productoptionprice',
            name='product_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_set', to='product.ProductOption', verbose_name='상품 옵션'),
        ),
    ]
