# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20170827_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinylInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('material', models.CharField(blank=True, max_length=60, verbose_name='재질')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': '상품정보 - 비닐',
                'verbose_name_plural': '상품정보 - 비닐 목록',
            },
        ),
    ]
