# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_vinylinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('vinyl', '비닐')], max_length=15, verbose_name='상품 타입'),
        ),
        migrations.AlterField(
            model_name='vinylinfo',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='상품'),
        ),
        migrations.AlterField(
            model_name='vinylinfo',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='두께'),
        ),
    ]
