# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.fields.custom_imagefield


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20170827_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', utils.fields.custom_imagefield.DefaultStaticImageField(blank=True, upload_to='product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
