# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptionprice',
            name='price',
            field=models.IntegerField(default=0, verbose_name='단위가격'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.IntegerField(default=0, verbose_name='단위가격'),
        ),
    ]
