# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': '주문정보', 'verbose_name_plural': '주문정보 목록'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': '주문항목', 'verbose_name_plural': '주문항목 목록'},
        ),
    ]
